import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
      <nav className='h-[56] flex justify-center items-center bg-indigo-700'>
        <Link className='mx-8 font-bold' href="/">home</Link>
        <Link className='mx-8' href="/about">about</Link>
        <Link className='mx-8' href="/dashboard">dashboard</Link>
        <Link className='mx-8' href="/contact">contact</Link>
      </nav>
        {children}
        
        </body>
    </html>
  )
}
